export const projectList = [
  {
    video: '',
    image: '/videos/myQue.webp',
    title: 'моя очередь',
    techs: [
      'моя очередь',
      'react',
      'реакт',
      'react router dom v5/6',
      'redux',
      'редакс',
      'toolkit',
      'тулкит',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'mui',
      'material ui',
      'материал',
      'react hook form',
      'yup',
      'toastify',
    ],
    icons: [
      'react',
      'react router dom v5/6',
      'redux',
      'toolkit',
      'spa',
      'html',
      'css',
      'ts',
      'mui',
      'react hook form',
      'yup',
      'toastify',
      'axios',
    ],
    tasks:
      'Регистрация пользователя. Валидация форм (react hook form). Разработка функций личного кабинета. Работа с файлами, видео (REST API). Работа с таблицами Material UI',
    code: '',
    demo: 'https://eq.loes.ru/',
  },
  {
    video: '',
    image: '/videos/gbzu.webp',
    title: 'ГБУЗ РБ',
    techs: [
      'ГБУЗ РБ',
      'react',
      'реакт',
      'react router dom v5/6',
      'redux',
      'редакс',
      'spa',
      'спа',
      'toolkit',
      'radix ui',
      'радикс юай',
      'storybook',
      'сторибук',
      'тулкит',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'mui',
      'material ui',
      'материал',
      'react hook form',
      'yup',
    ],
    icons: [
      'react',
      'react router dom v5/6',
      'redux',
      'radix ui',
      'storybook',
      'toolkit',
      'spa',
      'html',
      'css',
      'ts',
      'mui',
      'react hook form',
      'yup',
      'toastify',
      'axios',
    ],
    tasks:
      'Разработка функционала личного кабинета. Создание чата на Websocket (websocket.io. Работа с системой внутреннего документооборота. Написание unit tests (jest). Работа с Radix UI, Storybook. Работа с анимациями (animista.net)',
    code: '',
    demo: 'https://gkb5ufa.ru/',
  },
  {
    video: '/videos/chitaAuto.mp4',
    title: 'chita-auto',
    techs: [
      'chita-auto',
      'next js',
      'некст',
      'app router',
      'ssr',
      'сср',
      'ssg',
      'ссг',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'tailwind',
      'тайлвинд',
      'дизайн',
      'design',
      'figma',
      'фигма',
    ],
    icons: [
      'next js',
      'app router',
      'ssr',
      'ssg',
      'html',
      'css',
      'ts',
      'radix ui',
      'tailwind',
      'design',
      'figma',
    ],
    tasks:
      'Лендинг аренда авто. Отзывы пользователей. Галерея фото авто. Форма обратной связи.',
    code: 'https://github.com/AlexeYankov/chitaAvto',
    demo: 'https://chita-avto.vercel.app/',
  },
  {
    video: '/videos/portfolio1.mp4',
    title: 'Portfolio v 1.0',
    techs: [
      'Portfolio v 1.0',
      'react',
      'реакт',
      'react router dom v5/6',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'scss',
      'ts',
      'typescript',
      'тайпскрипт',
      'материал',
      'react hook form',
    ],
    icons: ['react', 'react router dom v5/6', 'spa', 'html', 'scss', 'ts'],
    tasks:
      'Ленивая подгрузка компонент. Работа с анимацией, keyframes. Адаптивная вёрстка.',
    code: 'https://github.com/AlexeYankov/portfolioYankovAV',
    demo: 'https://alexeyankov.github.io/portfolioYankovAV/',
  },
  {
    video: '/videos/reactQuery.mp4',
    title: 'Flash cards (RTK QUERY)',
    techs: [
      'Flash cards',
      'react',
      'реакт',
      'react router dom v5/6',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'материал',
      'react hook form',
      'i18',
      'мультиязычность',
    ],
    icons: [
      'react',
      'react router dom v5/6',
      'spa',
      'html',
      'scss',
      'ts',
      'zod',
      'react hook form',
      'redux toolkit',
      'storybook',
      'axios',
    ],
    tasks:
      'Регистрация пользователей. Фильтрация, сортировка данных. Добавление, удаление карточек. Мультиязычность. Изменение настоек профиля. Настройки пагинации.',
    code: 'https://github.com/AlexeYankov/LearningCards',
    demo: 'https://learning-cards-beige.vercel.app/',
  },
  {
    video: '/videos/rocketBusiness.mp4',
    title: 'Тестовое задание Rocket Business',
    techs: [
      'Тестовое задание Rocket Business',
      'react',
      'реакт',
      'react router dom v5/6',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'тестовое',
      'test',
    ],
    icons: ['react', 'react router dom v5/6', 'spa', 'html', 'scss', 'ts'],
    tasks:
      'Лендинг. Тестовое задание, бекенд PHP. Адаптивная вёрстка. Отправка формы на PHP сервер.',
    code: 'https://github.com/AlexeYankov/Rocket_Business',
    demo: 'https://rocket-business-gamma.vercel.app/',
  },
  {
    video: '/videos/apptrix.mp4',
    title: 'Тестовое задание APPTRIX',
    techs: [
      'Тестовое задание APPTRIX',
      'react router dom v5/6',
      'redux',
      'редакс',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'react-query',
      'реакт квери',
      'zustand',
      'зустанд',
      'toastify',
      'firebase',
      'фаербейс',
      'yup',
      'i18',
      'мультиязычность',
      'тестовое',
      'test',
    ],
    icons: [
      'spa',
      'redux',
      'react router dom v5/6',
      'html',
      'css',
      'ts',
      'toastify',
      'firebase',
      'yup',
      'react hook form',
      'i18',
    ],
    tasks:
      'Регистрация пользователей. Оформление заказов. Мультиязычность. Корзина пользователя, история заказов. Бекенд реализован на Firebase.',
    code: 'https://github.com/AlexeYankov/Empty',
    demo: 'https://empty-flame.vercel.app/',
  },
  {
    video: '/videos/reactQuery.mp4',
    title: 'Flash cards (react-query)',
    techs: [
      'Flash cards',
      'next js',
      'некст',
      'app router',
      'ssr',
      'сср',
      'ssg',
      'ссг',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'chackra ui',
      'чакра',
      'react-query',
      'реакт квери',
      'zustand',
      'зустанд',
      'toastify',
    ],
    icons: [
      'next js',
      'app router',
      'ssr',
      'ssg',
      'zustand',
      'react-query',
      'html',
      'css',
      'ts',
      'chackra ui',
      'toastify',
      'yup',
      'react hook form',
    ],
    tasks:
      'Регистрация пользователей. Фильтрация, сортировка данных. Добавление, удаление карточек. Изменение настоек профиля. Настройки пагинации.',
    code: 'https://github.com/AlexeYankov/myNextJSApp',
    demo: 'https://my-next-js-app-delta.vercel.app/',
  },
  {
    video: '/videos/Inctagramm.mp4',
    title: 'Inctagramm',
    techs: [
      'Inctagramm',
      'next js',
      'некст',
      'app router',
      'ssr',
      'сср',
      'ssg',
      'ссг',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'scss',
      'radix ui',
      'радикс',
      'react hook form',
      'yup',
      'i18',
      'мультиязычность',
    ],
    icons: [
      'next js',
      'app router',
      'ssr',
      'ssg',
      'html',
      'css',
      'ts',
      'radix ui',
      'i18',
      'react hook form',
      'yup',
    ],
    tasks:
      'Регистрация, авторизация пользователей. Восстановление пароля. Редактирование настроек профиля. Мультиязычность. Загрузка фотографий. Создание постов. ',
    code: 'https://github.com/FightersForJustice/Inctagram-Next-AppDir',
    demo: 'https://inctagramm.vercel.app/',
  },
  {
    video: '',
    image: '/videos/design.webp',
    title: 'buddy (дизайн)',
    techs: ['дизайн', 'design', 'figma', 'фигма', 'buddy (дизайн)'],
    icons: ['design', 'figma'],
    tasks: 'Разработка прототипа дизайна в Figma',
    code: 'https://github.com/AlexeYankov/designSocialnetwork',
    demo: '',
  },
  {
    video: '/videos/itrum.mp4',
    title: 'Itrum',
    techs: [
      'html',
      'хтмл',
      'css',
      'figma',
      'фигма',
      'js',
      'джс',
      'жс'
    ],
    icons: [
      'html',
      'css',
      'js',
      'figma',
    ],
    tasks:
      'Лендинг. Тестовое задание. Адаптивная верстка. Vanila js, html, css.',
    code: 'https://github.com/AlexeYankov/Itrum',
    demo: 'https://itrum.vercel.app/',
  },
  {
    video: '/videos/buddy.mp4',
    title: 'buddy',
    techs: [
      'buddyact',
      'react',
      'реакт',
      'react router dom v5/6',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'материал',
      'react hook form',
      'дизайн',
      'design',
      'figma',
      'фигма',
    ],
    icons: [
      'react',
      'react router dom v5/6',
      'spa',
      'html',
      'scss',
      'ts',
      'zod',
      'react hook form',
      'redux toolkit',
      'storybook',
      'axios',
      'figma',
    ],
    tasks:
      'Авторизация пользователей. Редактирование настроек профиля. Создание постов. Ленивая загрузка компонент. React Suspense.',
    code: 'https://github.com/AlexeYankov/samuraiway',
    demo: 'https://alexeyankov.github.io/samuraiway/',
  },
  {
    video: '/videos/disent.mp4',
    title: 'Disent',
    techs: [
      'html',
      'хтмл',
      'css',
      'js',
      'джс',
      'жс',
      'ts',
      'typescript',
    ],
    icons: [
      'html',
      'css',
      'typescript',
      'chackra ui',
      'zustand',
      'toastify',
      'next js',
      'scss',
      'axios',
      'react query',
    ],
    tasks:
      'Тестовое задание. Разработать приложение для демонстрации данных, полученных из API сервиса. В приложении должен быть отображен список стран и по клику на страну должна открываться страница с подробностями о стране. Добавить обработку случая, когда API не возвращает данные или возвращает ошибку.     ',
    code: 'https://github.com/AlexeYankov/disent',
    demo: 'https://disent-psi.vercel.app/',
  },
];
