export const projectList = [
  {
    video: '',
    image: '/videos/myQue.webp',
    title: 'моя очередь',
    techs: [
      'моя очередь',
      'react',
      'реакт',
      'react router dom v5/6',
      'redux',
      'редакс',
      'toolkit',
      'тулкит',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'mui',
      'material ui',
      'материал',
      'react hook form',
      'yup',
      'toastify',
    ],
    icons: [
      'react',
      'react router dom v5/6',
      'redux',
      'toolkit',
      'spa',
      'html',
      'css',
      'ts',
      'mui',
      'react hook form',
      'yup',
      'toastify',
      'axios',
    ],
    tasks:
      'Регистрация пользователя. Валидация форм (react hook form). Разработка функций личного кабинета. Работа с файлами, видео (REST API). Работа с таблицами Material UI',
    code: '',
    demo: 'https://eq.loes.ru/',
  },
  {
    video: '',
    image: '/videos/gbzu.webp',
    title: 'ГБУЗ РБ',
    techs: [
      'ГБУЗ РБ',
      'react',
      'реакт',
      'react router dom v5/6',
      'redux',
      'редакс',
      'spa',
      'спа',
      'toolkit',
      'radix ui',
      'радикс юай',
      'storybook',
      'сторибук',
      'тулкит',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'mui',
      'material ui',
      'материал',
      'react hook form',
      'yup',
    ],
    icons: [
      'react',
      'react router dom v5/6',
      'redux',
      'radix ui',
      'storybook',
      'toolkit',
      'spa',
      'html',
      'css',
      'ts',
      'mui',
      'react hook form',
      'yup',
      'toastify',
      'axios',
    ],
    tasks:
      'Разработка функционала личного кабинета. Создание чата на Websocket (websocket.io. Работа с системой внутреннего документооборота. Написание unit tests (jest). Работа с Radix UI, Storybook. Работа с анимациями (animista.net)',
    code: '',
    demo: 'https://gkb5ufa.ru/',
  },
  {
    video: '/videos/chitaAuto.mp4',
    title: 'chita-auto',
    techs: [
      'chita-auto',
      'next js',
      'некст',
      'app router',
      'ssr',
      'сср',
      'ssg',
      'ссг',
      'html',
      'хтмл',
      'css',
      'ts',
      'typescript',
      'тайпскрипт',
      'tailwind',
      'тайлвинд',
      'дизайн',
      'design',
      'figma',
      'фигма',
    ],
    icons: [
      'next js',
      'app router',
      'ssr',
      'ssg',
      'html',
      'css',
      'ts',
      'radix ui',
      'tailwind',
      'design',
      'figma',
    ],
    tasks:
      'Лендинг аренда авто. Отзывы пользователей. Галерея фото авто. Форма обратной связи.',
    code: 'https://github.com/AlexeYankov/chitaAvto',
    demo: 'https://chita-avto.vercel.app/',
  },
  {
    video: '/videos/portfolio1.mp4',
    title: 'Portfolio v 1.0',
    techs: [
      'Portfolio v 1.0',
      'react',
      'реакт',
      'react router dom v5/6',
      'spa',
      'спа',
      'html',
      'хтмл',
      'css',
      'scss',
      'ts',
      'typescript',
      'тайпскрипт',
      'материал',
      'react hook form',
    ],
    icons: ['react', 'react router dom v5/6', 'spa', 'html', 'scss', 'ts'],
    tasks:
      'Ленивая подгрузка компонент. Работа с анимацией, keyframes. Адаптивная вёрстка.',
    code: 'https://github.com/AlexeYankov/portfolioYankovAV',
    demo: 'https://alexeyankov.github.io/portfolioYankovAV/',
  },
];
